"""Write the fitted geometry into the website: React data module, favicon, OG image.

    python gen_site_assets.py      (from anywhere)

src/components/logoGeometry.js   generated constants for <LogoMark> (do not edit by hand)
public/favicon.svg               static mark on a rounded tile
public/og-image.svg              only the mark group is replaced
"""
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
SITE = HERE.parents[3]
G = json.loads((HERE.parent / 'fit_work' / 'geometry.json').read_text())
T = json.loads((HERE.parent / 'fit_work' / 'motion_timing.json').read_text())
BLUE, GRAY = G['colors']['blue'], G['colors']['gray']
LK = json.loads((HERE.parents[1] / 'lockup' / 'fit_work' / 'lockup_frame.json').read_text())
WM = json.loads((HERE.parents[1] / 'lockup' / 'fit_work' / 'wordmark.json').read_text())


def num(v):
    s = f'{v:.2f}'.rstrip('0').rstrip('.')
    return '0' if s == '-0' else s


def rect_js(r, extra=''):
    return f"{{ x: {num(r['x'])}, y: {num(r['y'])}, width: {num(r['width'])}, height: {num(r['height'])}{extra} }}"


hangers = [rect_js(r, f', step: {i % 3 + 1}') for i, r in enumerate(G['hangers']['left'] + G['hangers']['right'])]
js = f"""// Generated by brand/logo-motion/outputs/motion_work/gen_site_assets.py from the fitted
// master vector (brand/logo-motion/logo.svg). Do not edit by hand: re-run the generator.

export const VIEW_BOX = '{T['viewBox']}'

/** Ring: outer ellipse + inner circle, cut by two mirrored straight faces. */
export const ARC = '{G['arc']['d']}'

/** Deck: a crescent of four cubic curves with sharp tips. */
export const DECK = '{G['deck']['d']}'

export const LEGS = [
  '{G['legs'][0]}',
  '{G['legs'][1]}',
]

export const CROSSBARS = [
{chr(10).join('  ' + rect_js(r) + ',' for r in G['crossbars'])}
]

/** Tapered cables; their hidden ends close inside the tower legs. */
export const CABLES = [
  '{G['cables']['left']}',
  '{G['cables']['right']}',
]

/** step = drop order (1 nearest the tower). */
export const HANGERS = [
{chr(10).join('  ' + h + ',' for h in hangers)}
]

/** Motion scaffolding: draw-on pens (pathLength 1) and the clip the tower rises through. */
export const CABLE_PENS = [
  '{T['pens']['cable_l']}',
  '{T['pens']['cable_r']}',
]
export const CABLE_PEN_WIDTH = {T['pens']['cable_width']}
export const ARC_PENS = [
  '{T['pens']['arc_l']}',
  '{T['pens']['arc_r']}',
]
export const ARC_PEN_WIDTH = {T['pens']['arc_width']}
export const RISE_CLIP = '{T['rise_clip']}'

/** Lockup (About card): the mark under MARK_TRANSFORM + Montserrat wght 630 outlines. */
export const LOCKUP_VIEW_BOX = '{LK['viewBox']}'
export const LOCKUP_MARK_TRANSFORM = '{LK['mark_transform']}'
export const WORDMARK_LINE_1 = [
{chr(10).join("  '" + g['d'] + "', // " + g['char'] for g in WM['line1'])}
]
export const WORDMARK_LINE_2 = [
{chr(10).join("  '" + g['d'] + "', // " + g['char'] for g in WM['line2'])}
]
"""
(SITE / 'src' / 'components' / 'logoGeometry.js').write_text(js, encoding='utf-8')


def mark_group(transform, indent='  '):
    rect = lambda r: f'<rect x="{num(r["x"])}" y="{num(r["y"])}" width="{num(r["width"])}" height="{num(r["height"])}"/>'
    i2 = indent + '  '
    return '\n'.join([
        f'{indent}<g transform="{transform}">',
        f'{i2}<g fill="{GRAY}">',
        *[f'{i2}  <path d="{d}"/>' for d in G['legs']],
        *[f'{i2}  {rect(r)}' for r in G['crossbars']],
        *[f'{i2}  <path d="{d}"/>' for d in (G['cables']['left'], G['cables']['right'])],
        *[f'{i2}  {rect(r)}' for r in G['hangers']['left'] + G['hangers']['right']],
        f'{i2}</g>',
        f'{i2}<path fill="{BLUE}" d="{G["deck"]["d"]}"/>',
        f'{i2}<path fill="{BLUE}" d="{G["arc"]["d"]}"/>',
        f'{indent}</g>'])


# content bbox centre (axis 512, y midway between the ring top and the deck tips)
cx, cy = G['axis'], (G['arc']['outer'][1] - G['arc']['outer'][3] + G['deck']['top'][3][1]) / 2
(SITE / 'public' / 'favicon.svg').write_text(
    '<svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">\n'
    '  <rect width="512" height="512" rx="96" fill="#FEFEFE"/>\n'
    + mark_group(f'translate(256 256) scale(0.64) translate({num(-cx)} {num(-cy)})') + '\n</svg>\n', encoding='utf-8')

og_path = SITE / 'public' / 'og-image.svg'
og = og_path.read_text(encoding='utf-8')
x0 = G['deck']['top'][3][0]; y0 = G['arc']['outer'][1] - G['arc']['outer'][3]
og, n = re.subn(r'  <g transform="translate\(86 150\)[^"]*">.*?\n  </g>\n',
                lambda _: mark_group(f'translate(86 150) scale(0.3) translate({num(-x0)} {num(-y0)})') + '\n', og, flags=re.S)
assert n == 1, 'og mark block not found'
og_path.write_text(og, encoding='utf-8')
print('wrote logoGeometry.js, favicon.svg, og-image.svg; mark centre', num(cx), num(cy))

# ---------------------------------------------------------------- index.css: generated motion block
css_path = SITE / 'src' / 'index.css'
css = css_path.read_text(encoding='utf-8')
motion = (HERE.parents[1] / 'motion.css').read_text(encoding='utf-8').strip('\n')
START, END = '/* logo-motion:start */', '/* logo-motion:end */'
block = '\n'.join([
    START,
    '/* Generated from brand/logo-motion/motion.css by gen_site_assets.py — edit there, then re-run. */',
    "@property --jsd-rise {\n  syntax: '<length>';\n  inherits: false;\n  initial-value: 0px;\n}",
    '',
    '@media (prefers-reduced-motion: no-preference) {',
    *[('  ' + line) if line.strip() else '' for line in motion.splitlines()],
    '}',
    END])
if START in css:
    css = css[:css.index(START)] + block + css[css.index(END) + len(END):]
else:
    anchor = '.marquee-paused:hover .marquee-track {\n  animation-play-state: paused;\n}\n'
    assert anchor in css, 'index.css anchor moved'
    css = css.replace(anchor, anchor + '\n' + block + '\n', 1)
css_path.write_text(css, encoding='utf-8')
print('updated index.css logo-motion block')
